services:
  - type: web
    name: threads-spring
    env: docker
    plan: free
    buildCommand: cd threads && mvn clean package
    startCommand: cd threads && java -Dserver.port=$PORT -jar target/threads-0.0.1-SNAPSHOT.jar
    region: oregon
    branch: main
    rootDir: .
    dockerfilePath: Dockerfile