[versions]
agp = "8.7.3"
junit = "4.13.2"
junitVersion = "1.2.1"
espressoCore = "3.6.1"
appcompat = "1.7.0"
material = "1.12.0"
activity = "1.10.0"
constraintlayout = "2.2.0"
retrofit = "2.9.0"
converter-gson = "2.9.0"
logging-interceptor = "3.12.0"
glide = "4.16.0"
glideCompiler = "4.16.0"
okhttp= "4.11.0"
converterScalars = "2.9.0"
lombok = "1.18.30"
socketio-client = "2.0.1"
stompProtocolAndroid = "1.6.6"
rxJava = "2.2.21"

[libraries]
junit = { group = "junit", name = "junit", version.ref = "junit" }
ext-junit = { group = "androidx.test.ext", name = "junit", version.ref = "junitVersion" }
espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espressoCore" }
appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
material = { group = "com.google.android.material", name = "material", version.ref = "material" }
activity = { group = "androidx.activity", name = "activity", version.ref = "activity" }
constraintlayout = { group = "androidx.constraintlayout", name = "constraintlayout", version.ref = "constraintlayout" }
retrofit = { module = "com.squareup.retrofit2:retrofit", version.ref = "retrofit" }
converter-gson = { module = "com.squareup.retrofit2:converter-gson", version.ref = "converter-gson" }
logging-interceptor = { module = "com.squareup.okhttp3:logging-interceptor", version.ref = "logging-interceptor" }
glide = { module = "com.github.bumptech.glide:glide", version.ref = "glide" }
glideCompiler = { module = "com.github.bumptech.glide:compiler", version.ref = "glideCompiler" }
okhttp-logging = { group = "com.squareup.okhttp3", name = "logging-interceptor", version.ref = "okhttp" }
converter-scalars = { group = "com.squareup.retrofit2", name = "converter-scalars", version.ref = "converterScalars" }
lombok = { module = "org.projectlombok:lombok", version.ref = "lombok" }
lombok-processor = { module = "org.projectlombok:lombok", version.ref = "lombok" }
socketio-client = { module = "io.socket:socket.io-client", version.ref = "socketio-client" }
stompProtocolAndroid = { module = "com.github.NaikSoftware:StompProtocolAndroid", version.ref = "stompProtocolAndroid" }
rxJava = { module = "io.reactivex.rxjava2:rxjava", version.ref = "rxJava" }
okhttp = { module = "com.squareup.okhttp3:okhttp", version.ref = "okhttp" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }

